# Generated by Django 5.0.1 on 2024-02-04 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_ID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("level", models.CharField(max_length=2)),
                ("price", models.IntegerField()),
                ("duration_in_weeks", models.CharField(max_length=20)),
                ("number_of_lessons", models.IntegerField()),
                ("number_of_hours_with_native", models.IntegerField()),
                ("type", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("language_ID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("iso_code", models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("student_ID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("surname", models.CharField(max_length=25)),
                ("phone_number", models.CharField(max_length=12)),
                ("email", models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Language_Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PolyglotApp.course",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PolyglotApp.language",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrolment",
            fields=[
                ("enrolment_ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PolyglotApp.course",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PolyglotApp.language",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PolyglotApp.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("teacher_ID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("surname", models.CharField(max_length=25)),
                ("middle_name", models.CharField(max_length=25, null=True)),
                ("level", models.CharField(max_length=2)),
                ("phone_number", models.CharField(max_length=12)),
                ("email", models.CharField(max_length=30, null=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PolyglotApp.language",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course_Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PolyglotApp.course",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PolyglotApp.teacher",
                    ),
                ),
            ],
        ),
    ]
